version: '3.7'

networks:
  microservice-network:
    driver: bridge

services:

  # service_1:
  #   image: service_1_image
  #   ports:
  #     - "4001:4001"
  #   networks:
  #     - microservice-network

  service_2:
    image: service_2_image
    networks:
      - microservice-network

  service_3:
    image: service_3_image
    networks:
      - microservice-network

  service_1_tests:
    image: service_1_image
    command: sh -cx "npm test"
    depends_on:
      - service_2
      - service_3
    networks:
      - microservice-network
